### ISSUE TITLE
"make test" task does not work during a pipeline

### ISSUE THREAD

**Issue by g0blin79** [bmeme/drupal-docker-build#4]
If I run this build with a working Drupal project in a Gitlab pipeline, `make test` task failed with this error

```
============ Start test on Drupal environment...
bin/do test
 > >> Exec Behat tests 
Traceback (most recent call last):
  File "bin/docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 68, in main
  File "compose/cli/main.py", line 118, in perform_command
  File "compose/cli/main.py", line 454, in exec_command
  File "site-packages/dockerpty/pty.py", line 338, in start
  File "site-packages/dockerpty/io.py", line 32, in set_blocking
ValueError: file descriptor cannot be a negative integer (-1)
Failed to execute script docker-compose
Traceback (most recent call last):
  File "bin/docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 68, in main
  File "compose/cli/main.py", line 118, in perform_command
  File "compose/cli/main.py", line 454, in exec_command
  File "site-packages/dockerpty/pty.py", line 338, in start
  File "site-packages/dockerpty/io.py", line 32, in set_blocking
ValueError: file descriptor cannot be a negative integer (-1)
```
Seems to be related to this: https://github.com/docker/compose/issues/3352

**Comment by g0blin79** [comment]
now all exec commands are executed with docker exec and not with docker-compose exec.
